version: '3.4'

services:
  estoque.api:
    image: ${DOCKER_REGISTRY-}estoqueapi
    container_name: estoque.api
    build:
      context: .
      dockerfile: Estoque.API\Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  estoque.database:
    image: postgres:latest
    container_name: estoque.database
    environment:
      - POSTGRES_DB=estoque
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/products-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  estoque.cache:
    image: redis:latest
    container_name: estoque.cache
    restart: always
    ports:
      - '6379:6379'

  keycloak.database:
    image: postgres:latest
    container_name: keycloak.database
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  keycloak.app:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak.app
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak.database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - 9090:8080
    depends_on:
      - keycloak.database

volumes:
  postgres_data:

